[build]
  publish = "flutter_app/build/web"
  command = 'cd flutter_app && if ! command -v flutter &> /dev/null; then echo '\''Flutter not found, installing...'\''; git clone https://github.com/flutter/flutter.git --depth 1 --branch stable $HOME/flutter-sdk; export PATH="$HOME/flutter-sdk/bin:$PATH"; flutter --version; else echo '\''Flutter found, using system version.'\''; flutter --version; fi'

[build.environment]
  FLUTTER_VERSION = "3.10.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
