[build]
  publish = "flutter_app/build/web"
  command = "cd flutter_app && flutter build web"

[[headers]]
  for = "/flutter.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/canvaskit.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/canvaskit.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
