[build]
  publish = "flutter_app/build/web"
  command = "cd flutter_app && (if ! command -v flutter &> /dev/null; then echo 'Flutter not found, installing...'; git clone https://github.com/flutter/flutter.git --depth 1 --branch stable /opt/flutter; export PATH=\"$PATH:/opt/flutter/bin\"; else echo 'Flutter found, using system version.'; fi) && flutter channel stable && flutter doctor && flutter build web --verbose"

[build.environment]
  FLUTTER_VERSION = "3.10.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
