[build]
  publish = "flutter_app/build/web"
  command = "cd flutter_app && flutter channel stable && flutter doctor && flutter build web --verbose"

[build.environment]
  FLUTTER_VERSION = "3.10.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
