[build]
  command = 'if ! command -v flutter &> /dev/null; then git clone https://github.com/flutter/flutter.git $HOME/flutter-sdk && export PATH="$PATH:$HOME/flutter-sdk/bin"; fi && flutter --version && cd flutter_app && flutter build web --release'
  publish = "flutter_app/build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.5"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200