name: todolist_flutter
description: A beautiful and modern todo list application built with Flutter.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Date & Time
  intl: ^0.18.1
  
  # Icons
  flutter_svg: ^2.0.9
  
  # Utils
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf